using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using EnvSecured.Core.Models;
using EnvSecured.Core.Services;

namespace EnvSecured.Core.Rendering
{
    public sealed class RenderService
    {
        private const string Header =
            "#########################################\r\n" +
            "# AUTO-GENERATED BY ENVSECURED STUDIO\r\n" +
            "# DO NOT EDIT MANUALLY\r\n" +
            "# Edit values in EnvSecured Studio instead\r\n" +
            "#########################################\r\n";

        public void RenderRuntimeEnv(ProjectModel project, string outputRoot, string serviceId, string environmentId)
        {
            ValidateUniqueOutputFolders(project);
            var service = project.Services.Single(s => s.Id == serviceId);
            var environment = project.Environments.Single(e => e.Id == environmentId);
            var effective = new EffectiveConfigService().Build(project, serviceId, environmentId).Where(x => !x.Missing).ToDictionary(x => x.Variable.Id);
            var keys = project.Variables
                .Where(v => ProjectService.IsVariableUsedByService(project, v.Id, serviceId))
                .OrderBy(v => v.SortOrder)
                .ThenBy(v => v.Key);
            var lines = new List<string> { Header.TrimEnd() };

            foreach (var variable in keys)
            {
                if (effective.TryGetValue(variable.Id, out var value))
                {
                    lines.Add($"{value.Variable.Key}={value.Value}");
                }
            }

            var folder = Path.Combine(outputRoot, "apps", OutputFolderPathSegment(service));
            Directory.CreateDirectory(folder);
            File.WriteAllLines(Path.Combine(folder, $".env.{environment.Name}.local"), lines);
        }

        public void ExportExamples(ProjectModel project, string outputRoot)
        {
            ValidateUniqueOutputFolders(project);
            foreach (var service in project.Services.Where(s => s.IsActive))
            {
                var lines = new List<string> { Header.TrimEnd() };
                var variables = project.Variables
                    .Where(v => ProjectService.IsVariableUsedByService(project, v.Id, service.Id))
                    .OrderBy(v => v.SortOrder)
                    .ThenBy(v => v.Key);
                foreach (var variable in variables)
                {
                    var contract = project.Contracts.FirstOrDefault(c => c.VariableId == variable.Id && c.ServiceId == service.Id && !c.Excluded);
                    lines.Add($"{variable.Key}={contract?.DemoValue ?? variable.DemoValue ?? string.Empty}");
                }

                var folder = Path.Combine(outputRoot, "apps", OutputFolderPathSegment(service));
                Directory.CreateDirectory(folder);
                File.WriteAllLines(Path.Combine(folder, ".env.example"), lines);
            }
        }

        private static string OutputFolderPathSegment(ServiceModel service)
        {
            return service.OutputFolder == null ? service.Name : service.OutputFolder.Trim();
        }

        private static void ValidateUniqueOutputFolders(ProjectModel project)
        {
            var duplicate = project.Services
                .GroupBy(s => NormalizeOutputFolderKey(s.OutputFolder), StringComparer.OrdinalIgnoreCase)
                .FirstOrDefault(g => g.Count() > 1);
            if (duplicate != null)
            {
                throw new InvalidOperationException("Service output folder must be unique. Empty output folder can be used by only one service.");
            }
        }

        private static string NormalizeOutputFolderKey(string value)
        {
            return (value ?? string.Empty).Trim().Replace('/', '\\').Trim('\\');
        }

    }
}
