using System.Collections.Generic;
using System.IO;
using System.Linq;
using EnvSecured.Core.Models;
using EnvSecured.Core.Services;

namespace EnvSecured.Core.Rendering
{
    public sealed class RenderService
    {
        private const string Header =
            "#########################################\r\n" +
            "# AUTO-GENERATED BY ENVSECURED STUDIO\r\n" +
            "# DO NOT EDIT MANUALLY\r\n" +
            "# Edit values in EnvSecured Studio instead\r\n" +
            "#########################################\r\n";

        public void RenderRuntimeEnv(ProjectModel project, string outputRoot, string serviceId, string environmentId)
        {
            var service = project.Services.Single(s => s.Id == serviceId);
            var environment = project.Environments.Single(e => e.Id == environmentId);
            var effective = new EffectiveConfigService().Build(project, serviceId, environmentId).Where(x => !x.Missing).ToDictionary(x => x.Variable.Id);
            var keys = project.Variables
                .Where(v => IsVariableUsedByService(project, v.Id, serviceId))
                .OrderBy(v => v.SortOrder)
                .ThenBy(v => v.Key);
            var lines = new List<string> { Header.TrimEnd() };

            foreach (var variable in keys)
            {
                if (effective.TryGetValue(variable.Id, out var value))
                {
                    lines.Add($"{value.Variable.Key}={value.Value}");
                }
            }

            var folder = Path.Combine(outputRoot, "apps", service.OutputFolder ?? service.Name);
            Directory.CreateDirectory(folder);
            File.WriteAllLines(Path.Combine(folder, $".env.{environment.Name}.local"), lines);
        }

        public void ExportExamples(ProjectModel project, string outputRoot)
        {
            foreach (var service in project.Services.Where(s => s.IsActive))
            {
                var lines = new List<string> { Header.TrimEnd() };
                var variables = project.Variables
                    .Where(v => IsVariableUsedByService(project, v.Id, service.Id))
                    .OrderBy(v => v.SortOrder)
                    .ThenBy(v => v.Key);
                foreach (var variable in variables)
                {
                    var contract = project.Contracts.FirstOrDefault(c => c.VariableId == variable.Id && c.ServiceId == service.Id && !c.Excluded);
                    lines.Add($"{variable.Key}={contract?.ExampleValue ?? variable.DefaultExampleValue ?? string.Empty}");
                }

                var folder = Path.Combine(outputRoot, "apps", service.OutputFolder ?? service.Name);
                Directory.CreateDirectory(folder);
                File.WriteAllLines(Path.Combine(folder, ".env.example"), lines);
            }
        }

        private static bool IsVariableUsedByService(ProjectModel project, string variableId, string serviceId)
        {
            var contract = project.Contracts.FirstOrDefault(c => c.VariableId == variableId && c.ServiceId == serviceId);
            if (contract != null) return !contract.Excluded;
            return project.Values.Any(v => v.VariableId == variableId && v.Scope == ValueScope.Global && v.ServiceId == null && v.EnvironmentId == null);
        }
    }
}
